### ISSUE TITLE
Uddl.xtext file

### ISSUE THREAD

**Issue by SKilgori** [Epistimis/UDDL#30]
After following the instructions I encountered an error when I tried to run the Uddl.xtext file
it's showing me this error message
An internal error occurred during: "Launching GenerateUddl.mwe2".
Model not available for com.epistimis.uddl

**Comment by steve-hickman-epistimis** [comment]
Please post a log file capturing the Console output. That will help me debug it.

**Comment by SKilgori** [comment]
[error.log](https://github.com/Epistimis/UDDL/files/10742880/error.log)
I've tried the solutions and started over but nothing worked I've attached the log file here.

**Comment by steve-hickman-epistimis** [comment]
Looking at the log, I see the following:
1) The environment variable HOME is not set. Don't know if this will make a difference but you might as well address it.

2) MESSAGE Synchronize project UDDL failed due to an error connecting to the Gradle build.
!STACK 0
org.gradle.tooling.GradleConnectionException: Could not install Gradle distribution from 'https://services.gradle.org/distributions/gradle-7.4.2-bin.zip'.
Caused by: java.io.IOException: Downloading from https://services.gradle.org/distributions/gradle-7.4.2-bin.zip failed: timeout
	at org.gradle.wrapper.Download.downloadInternal(Download.java:122)
	at org.gradle.wrapper.Download.download(Download.java:80)
	at org.gradle.tooling.internal.consumer.DistributionInstaller$AsyncDownload$1.run(DistributionInstaller.java:182)
Caused by: java.net.SocketTimeoutException: Read timed out

It looks like your internet connection may be too slow or intermittent.
