### ISSUE TITLE
Outline pane does not show structure of UDDL file

### ISSUE THREAD

**Issue by DanielOkyere** [Epistimis/UDDL#36]
**Describe the bug**

I have successfully gone through the instructions to the point where the UDDL_SDM_Min.uddl opened in another project. How ever I did not get any prompt to convert to XText but it was not greyed out. Also the. Outline page did not show any structure of UDDL

<img width="1680" alt="Screenshot 2023-02-20 at 2 58 25 PM" src="https://user-images.githubusercontent.com/25333167/220141382-2f619c90-a098-41eb-8d63-55ee7ab1c510.png">

**Comment by DanielOkyere** [comment]
@steve-hickman-epistimis 
I just went through the resource you pointed out. Now am getting new errors.

----------------------- Console output --------------------------------------
!SESSION 2023-02-20 15:31:13.679 -----------------------------------------------
eclipse.buildId=4.26.0.20221201-1200
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_GH
Framework arguments:  -product org.eclipse.epp.package.dsl.product
Command-line arguments:  -product org.eclipse.epp.package.dsl.product -data /Users/danielokyere/eclipse-workspace/../runtime-daniel_new_configurations -dev file:/Users/danielokyere/eclipse-workspace/.metadata/.plugins/org.eclipse.pde.core/daniel_new_configurations/dev.properties -os macosx -ws cocoa -arch x86_64 -consoleLog

!ENTRY com.epistimis.uddl 4 0 2023-02-20 15:31:17.652
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: com.epistimis.uddl [7]
  Unresolved requirement: Require-Bundle: org.eclipse.emf.validation; bundle-version="1.8.1"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1852)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1845)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1786)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1750)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1672)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

!ENTRY com.epistimis.uddl.ide 4 0 2023-02-20 15:31:17.658
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: com.epistimis.uddl.ide [8]
  Unresolved requirement: Require-Bundle: com.epistimis.uddl
    -> Bundle-SymbolicName: com.epistimis.uddl; bundle-version="1.0.0.qualifier"; singleton:="true"
       com.epistimis.uddl [7]
         Unresolved requirement: Require-Bundle: org.eclipse.emf.validation; bundle-version="1.8.1"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1852)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1845)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1786)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1750)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1672)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

!ENTRY com.epistimis.uddl.tests 4 0 2023-02-20 15:31:17.659
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: com.epistimis.uddl.tests [14]
  Unresolved requirement: Require-Bundle: com.epistimis.uddl
    -> Bundle-SymbolicName: com.epistimis.uddl; bundle-version="1.0.0.qualifier"; singleton:="true"
       com.epistimis.uddl [7]
         Unresolved requirement: Require-Bundle: org.eclipse.emf.validation; bundle-version="1.8.1"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1852)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1845)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1786)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1750)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1672)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

!ENTRY com.epistimis.uddl.ui 4 0 2023-02-20 15:31:17.664
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: com.epistimis.uddl.ui [15]
  Unresolved requirement: Require-Bundle: com.epistimis.uddl
    -> Bundle-SymbolicName: com.epistimis.uddl; bundle-version="1.0.0.qualifier"; singleton:="true"
       com.epistimis.uddl [7]
         Unresolved requirement: Require-Bundle: org.eclipse.emf.validation; bundle-version="1.8.1"
  Unresolved requirement: Require-Bundle: com.epistimis.uddl.ide
    -> Bundle-SymbolicName: com.epistimis.uddl.ide; bundle-version="1.0.0.qualifier"; singleton:="true"
       com.epistimis.uddl.ide [8]
         Unresolved requirement: Require-Bundle: com.epistimis.uddl
           -> Bundle-SymbolicName: com.epistimis.uddl; bundle-version="1.0.0.qualifier"; singleton:="true"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1852)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1845)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1786)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1750)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1672)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

!ENTRY com.epistimis.uddl.ui.tests 4 0 2023-02-20 15:31:17.665
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: com.epistimis.uddl.ui.tests [16]
  Unresolved requirement: Require-Bundle: com.epistimis.uddl.ui
    -> Bundle-SymbolicName: com.epistimis.uddl.ui; bundle-version="1.0.0.qualifier"; singleton:="true"
       com.epistimis.uddl.ui [15]
         Unresolved requirement: Require-Bundle: com.epistimis.uddl
           -> Bundle-SymbolicName: com.epistimis.uddl; bundle-version="1.0.0.qualifier"; singleton:="true"
              com.epistimis.uddl [7]
                Unresolved requirement: Require-Bundle: org.eclipse.emf.validation; bundle-version="1.8.1"
         Unresolved requirement: Require-Bundle: com.epistimis.uddl.ide
           -> Bundle-SymbolicName: com.epistimis.uddl.ide; bundle-version="1.0.0.qualifier"; singleton:="true"
              com.epistimis.uddl.ide [8]
                Unresolved requirement: Require-Bundle: com.epistimis.uddl
                  -> Bundle-SymbolicName: com.epistimis.uddl; bundle-version="1.0.0.qualifier"; singleton:="true"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1852)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1845)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1786)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1750)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1672)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)

!ENTRY ch.qos.logback.classic 1 0 2023-02-20 15:31:19.966
!MESSAGE Activated before the state location was initialized. Retry after the state location is initialized.
15:31:24.150 [main] DEBUG org.eclipse.m2e.core.internal.project.registry.ProjectRegistryRefreshJob - Queued refresh request: []

!ENTRY ch.qos.logback.classic 1 0 2023-02-20 15:31:24.193
!MESSAGE Logback config file: /Users/danielokyere/runtime-daniel_new_configurations/.metadata/.plugins/org.eclipse.m2e.logback/logback.2.1.0.20221015-0744.xml

!ENTRY org.eclipse.jface 2 0 2023-02-20 15:31:27.499
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2023-02-20 15:31:27.499
!MESSAGE A conflict occurred for COMMAND+SHIFT+T:
Binding(COMMAND+SHIFT+T,
	ParameterizedCommand(Command(org.eclipse.jdt.ui.navigate.open.type,Open Type,
		Open a type in a Java editor,
		Category(org.eclipse.ui.category.navigate,Navigate,null,true),
		WorkbenchHandlerServiceHandler("org.eclipse.jdt.ui.navigate.open.type"),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(COMMAND+SHIFT+T,
	ParameterizedCommand(Command(org.eclipse.lsp4e.symbolinworkspace,Go to Symbol in Workspace,
		,
		Category(org.eclipse.lsp4e.category,Language Servers,null,true),
		WorkbenchHandlerServiceHandler("org.eclipse.lsp4e.symbolinworkspace"),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
!SUBENTRY 1 org.eclipse.jface 2 0 2023-02-20 15:31:27.500
!MESSAGE A conflict occurred for ALT+COMMAND+R:
Binding(ALT+COMMAND+R,
	ParameterizedCommand(Command(org.eclipse.ui.edit.rename,Rename,
		Rename the selected item,
		Category(org.eclipse.ui.category.file,File,null,true),
		WorkbenchHandlerServiceHandler("org.eclipse.ui.edit.rename"),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,cocoa,system)
Binding(ALT+COMMAND+R,
	ParameterizedCommand(Command(org.eclipse.jdt.ui.edit.text.java.rename.element,Rename - Refactoring ,
		Rename the selected element,
		Category(org.eclipse.jdt.ui.category.refactoring,Refactor - Java,Java Refactoring Actions,true),
		WorkbenchHandlerServiceHandler("org.eclipse.jdt.ui.edit.text.java.rename.element"),
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,cocoa,system)
2023-02-20 15:31:33.932 java[91343:4842581] nil host used in call to allowsSpecificHTTPSCertificateForHost
2023-02-20 15:31:33.933 java[91343:4842581] nil host used in call to allowsAnyHTTPSCertificateForHost:
2023-02-20 15:31:33.937 java[91343:4842581] nil host used in call to allowsSpecificHTTPSCertificateForHost
2023-02-20 15:31:33.937 java[91343:4842581] nil host used in call to allowsAnyHTTPSCertificateForHost:
2023-02-20 15:31:33.939 java[91343:4842581] nil host used in call to allowsSpecificHTTPSCertificateForHost
2023-02-20 15:31:33.939 java[91343:4842581] nil host used in call to allowsAnyHTTPSCertificateForHost:
2023-02-20 15:31:33.940 java[91343:4842581] nil host used in call to allowsSpecificHTTPSCertificateForHost
2023-02-20 15:31:33.940 java[91343:4842581] nil host used in call to allowsAnyHTTPSCertificateForHost:
2023-02-20 15:31:33.941 java[91343:4842581] nil host used in call to allowsSpecificHTTPSCertificateForHost
2023-02-20 15:31:33.941 java[91343:4842581] nil host used in call to allowsAnyHTTPSCertificateForHost:
2023-02-20 15:31:33.947 java[91343:4842581] nil host used in call to allowsSpecificHTTPSCertificateForHost
2023-02-20 15:31:33.948 java[91343:4842581] nil host used in call to allowsAnyHTTPSCertificateForHost:
2023-02-20 15:31:33.967 java[91343:4842581] nil host used in call to allowsSpecificHTTPSCertificateForHost
2023-02-20 15:31:33.968 java[91343:4842581] nil host used in call to allowsAnyHTTPSCertificateForHost:
2023-02-20 15:31:33.974 java[91343:4842581] nil host used in call to allowsSpecificHTTPSCertificateForHost
2023-02-20 15:31:33.977 java[91343:4842581] nil host used in call to allowsAnyHTTPSCertificateForHost:
2023-02-20 15:31:34.010 java[91343:4842581] nil host used in call to allowsSpecificHTTPSCertificateForHost
2023-02-20 15:31:34.015 java[91343:4842581] nil host used in call to allowsAnyHTTPSCertificateForHost:
2023-02-20 15:31:34.028 java[91343:4842581] nil host used in call to allowsSpecificHTTPSCertificateForHost
2023-02-20 15:31:34.043 java[91343:4842581] nil host used in call to allowsAnyHTTPSCertificateForHost:
2023-02-20 15:31:34.056 java[91343:4842581] nil host used in call to allowsSpecificHTTPSCertificateForHost
2023-02-20 15:31:34.056 java[91343:4842581] nil host used in call to allowsAnyHTTPSCertificateForHost:
2023-02-20 15:31:34.060 java[91343:4842581] nil host used in call to allowsSpecificHTTPSCertificateForHost
2023-02-20 15:31:34.062 java[91343:4842581] nil host used in call to allowsAnyHTTPSCertificateForHost:
2023-02-20 15:31:34.073 java[91343:4842581] nil host used in call to allowsSpecificHTTPSCertificateForHost
2023-02-20 15:31:34.074 java[91343:4842581] nil host used in call to allowsAnyHTTPSCertificateForHost:
2023-02-20 15:31:34.077 java[91343:4842581] nil host used in call to allowsSpecificHTTPSCertificateForHost
2023-02-20 15:31:34.077 java[91343:4842581] nil host used in call to allowsAnyHTTPSCertificateForHost:
2023-02-20 15:31:34.081 java[91343:4842581] nil host used in call to allowsSpecificHTTPSCertificateForHost
2023-02-20 15:31:34.082 java[91343:4842581] nil host used in call to allowsAnyHTTPSCertificateForHost:
2023-02-20 15:31:34.494 java[91343:4842581] nil host used in call to allowsSpecificHTTPSCertificateForHost
2023-02-20 15:31:34.494 java[91343:4842581] nil host used in call to allowsAnyHTTPSCertificateForHost:
2023-02-20 15:31:34.504 java[91343:4842581] nil host used in call to allowsSpecificHTTPSCertificateForHost
2023-02-20 15:31:34.504 java[91343:4842581] nil host used in call to allowsAnyHTTPSCertificateForHost:
2023-02-20 15:31:34.518 java[91343:4842581] nil host used in call to allowsSpecificHTTPSCertificateForHost
2023-02-20 15:31:34.518 java[91343:4842581] nil host used in call to allowsAnyHTTPSCertificateForHost:
2023-02-20 15:31:34.521 java[91343:4842581] nil host used in call to allowsSpecificHTTPSCertificateForHost
2023-02-20 15:31:34.521 java[91343:4842581] nil host used in call to allowsAnyHTTPSCertificateForHost:
2023-02-20 15:31:34.521 java[91343:4842581] nil host used in call to allowsSpecificHTTPSCertificateForHost
2023-02-20 15:31:34.521 java[91343:4842581] nil host used in call to allowsAnyHTTPSCertificateForHost:
2023-02-20 15:31:34.522 java[91343:4842581] nil host used in call to allowsSpecificHTTPSCertificateForHost
2023-02-20 15:31:34.522 java[91343:4842581] nil host used in call to allowsAnyHTTPSCertificateForHost:
2023-02-20 15:31:34.589 java[91343:4842581] *** WARNING: Method convertPointToBase: in class NSView is deprecated on 10.7 and later. It should not be used in new applications. 

--------------------------- Screen shots ----------------------------------------
<img width="1680" alt="Screenshot 2023-02-20 at 3 39 21 PM" src="https://user-images.githubusercontent.com/25333167/220149508-201c08f2-7979-4be5-8e24-f25f7cde3200.png">

<img width="1680" alt="Screenshot 2023-02-20 at 3 38 00 PM" src="https://user-images.githubusercontent.com/25333167/220149589-2e3571e8-9566-409c-9e67-4a4a22f64b6e.png">

**Comment by steve-hickman-epistimis** [comment]
You're getting those errors because you still have build errors in the first Eclipse.  Did you Generate XText Artifacts for both com.epistims.uddl and com.epistims.uddl.query? If not, do so. Then I suggest doing Project -> Clean to clean and rebuild all your projects.
